export const games = [
  { name: "Minecraft", challenge: 35, exploration: 95, social: 60, creativity: 100, narrative: 15 },
  { name: "Terraria", challenge: 65, exploration: 90, social: 55, creativity: 80, narrative: 20 },
  { name: "Stardew Valley", challenge: 20, exploration: 60, social: 40, creativity: 75, narrative: 50 },
  { name: "Elden Ring", challenge: 95, exploration: 90, social: 20, creativity: 10, narrative: 55 },
  { name: "Dark Souls III", challenge: 95, exploration: 75, social: 15, creativity: 10, narrative: 45 },
  { name: "Sekiro", challenge: 100, exploration: 40, social: 5, creativity: 5, narrative: 40 },
  { name: "Bloodborne", challenge: 95, exploration: 70, social: 10, creativity: 10, narrative: 50 },
  { name: "Skyrim", challenge: 45, exploration: 95, social: 25, creativity: 50, narrative: 75 },
  { name: "Oblivion", challenge: 40, exploration: 90, social: 20, creativity: 45, narrative: 70 },
  { name: "Morrowind", challenge: 60, exploration: 95, social: 15, creativity: 50, narrative: 70 },
  { name: "The Witcher 3", challenge: 50, exploration: 85, social: 15, creativity: 10, narrative: 95 },
  { name: "Cyberpunk 2077", challenge: 50, exploration: 85, social: 20, creativity: 20, narrative: 90 },
  { name: "Red Dead Redemption 2", challenge: 35, exploration: 90, social: 10, creativity: 15, narrative: 100 },
  { name: "GTA V", challenge: 40, exploration: 80, social: 70, creativity: 40, narrative: 65 },
  { name: "GTA San Andreas", challenge: 35, exploration: 75, social: 30, creativity: 25, narrative: 75 },
  { name: "Fallout: New Vegas", challenge: 50, exploration: 85, social: 20, creativity: 40, narrative: 90 },
  { name: "Fallout 4", challenge: 45, exploration: 80, social: 20, creativity: 65, narrative: 70 },
  { name: "Mass Effect 2", challenge: 45, exploration: 40, social: 25, creativity: 10, narrative: 95 },
  { name: "Dragon Age Origins", challenge: 55, exploration: 50, social: 20, creativity: 10, narrative: 95 },
  { name: "Baldur's Gate 3", challenge: 60, exploration: 80, social: 50, creativity: 70, narrative: 100 },

  { name: "Portal 2", challenge: 65, exploration: 25, social: 20, creativity: 15, narrative: 70 },
  { name: "Portal", challenge: 70, exploration: 20, social: 5, creativity: 15, narrative: 65 },
  { name: "Half-Life 2", challenge: 55, exploration: 40, social: 5, creativity: 5, narrative: 90 },
  { name: "Half-Life", challenge: 60, exploration: 35, social: 5, creativity: 5, narrative: 80 },
  { name: "BioShock", challenge: 55, exploration: 50, social: 5, creativity: 5, narrative: 90 },
  { name: "BioShock Infinite", challenge: 50, exploration: 40, social: 5, creativity: 5, narrative: 95 },
  { name: "Dishonored", challenge: 65, exploration: 75, social: 5, creativity: 60, narrative: 75 },
  { name: "Dishonored 2", challenge: 70, exploration: 80, social: 5, creativity: 70, narrative: 75 },
  { name: "Prey (2017)", challenge: 70, exploration: 85, social: 5, creativity: 75, narrative: 80 },
  { name: "Deus Ex Human Revolution", challenge: 60, exploration: 70, social: 5, creativity: 55, narrative: 85 },

  { name: "Hades", challenge: 80, exploration: 25, social: 5, creativity: 20, narrative: 80 },
  { name: "Dead Cells", challenge: 90, exploration: 20, social: 5, creativity: 15, narrative: 20 },
  { name: "Hollow Knight", challenge: 85, exploration: 95, social: 5, creativity: 10, narrative: 65 },
  { name: "Celeste", challenge: 95, exploration: 15, social: 5, creativity: 5, narrative: 75 },
  { name: "Cuphead", challenge: 95, exploration: 10, social: 15, creativity: 5, narrative: 25 },
  { name: "Ori and the Blind Forest", challenge: 70, exploration: 70, social: 5, creativity: 10, narrative: 80 },
  { name: "Ori and the Will of the Wisps", challenge: 75, exploration: 80, social: 5, creativity: 10, narrative: 85 },
  { name: "Undertale", challenge: 30, exploration: 40, social: 5, creativity: 25, narrative: 100 },
  { name: "Deltarune", challenge: 35, exploration: 45, social: 5, creativity: 25, narrative: 95 },
  { name: "Inside", challenge: 30, exploration: 30, social: 5, creativity: 10, narrative: 80 },

  { name: "Factorio", challenge: 85, exploration: 50, social: 20, creativity: 100, narrative: 5 },
  { name: "Satisfactory", challenge: 70, exploration: 75, social: 35, creativity: 95, narrative: 5 },
  { name: "Cities Skylines", challenge: 50, exploration: 10, social: 5, creativity: 95, narrative: 5 },
  { name: "RimWorld", challenge: 80, exploration: 40, social: 15, creativity: 95, narrative: 80 },
  { name: "Prison Architect", challenge: 60, exploration: 10, social: 5, creativity: 85, narrative: 20 },
  { name: "Planet Zoo", challenge: 35, exploration: 15, social: 5, creativity: 95, narrative: 10 },
  { name: "Planet Coaster", challenge: 30, exploration: 15, social: 5, creativity: 100, narrative: 10 },
  { name: "The Sims 4", challenge: 15, exploration: 30, social: 20, creativity: 95, narrative: 60 },
  { name: "The Sims 3", challenge: 20, exploration: 40, social: 20, creativity: 95, narrative: 65 },
  { name: "Spore", challenge: 20, exploration: 60, social: 15, creativity: 100, narrative: 20 },

  { name: "Valorant", challenge: 85, exploration: 5, social: 90, creativity: 15, narrative: 5 },
  { name: "Counter-Strike 2", challenge: 90, exploration: 5, social: 95, creativity: 10, narrative: 0 },
  { name: "Overwatch 2", challenge: 75, exploration: 5, social: 95, creativity: 20, narrative: 10 },
  { name: "Rainbow Six Siege", challenge: 90, exploration: 5, social: 90, creativity: 25, narrative: 5 },
  { name: "Apex Legends", challenge: 80, exploration: 40, social: 90, creativity: 15, narrative: 10 },
  { name: "Fortnite", challenge: 65, exploration: 60, social: 95, creativity: 80, narrative: 15 },
  { name: "PUBG", challenge: 75, exploration: 50, social: 85, creativity: 10, narrative: 5 },
  { name: "Team Fortress 2", challenge: 70, exploration: 10, social: 90, creativity: 25, narrative: 10 },
  { name: "Call of Duty MW", challenge: 70, exploration: 10, social: 80, creativity: 10, narrative: 20 },
  { name: "Battlefield 1", challenge: 65, exploration: 25, social: 85, creativity: 10, narrative: 25 },

  { name: "World of Warcraft", challenge: 55, exploration: 85, social: 100, creativity: 30, narrative: 70 },
  { name: "Final Fantasy XIV", challenge: 50, exploration: 80, social: 100, creativity: 25, narrative: 90 },
  { name: "Guild Wars 2", challenge: 50, exploration: 90, social: 95, creativity: 25, narrative: 70 },
  { name: "Black Desert Online", challenge: 60, exploration: 85, social: 80, creativity: 40, narrative: 30 },
  { name: "Runescape", challenge: 40, exploration: 85, social: 90, creativity: 30, narrative: 40 },
  { name: "Lost Ark", challenge: 65, exploration: 40, social: 80, creativity: 15, narrative: 45 },

  { name: "League of Legends", challenge: 85, exploration: 5, social: 95, creativity: 15, narrative: 5 },
  { name: "Dota 2", challenge: 95, exploration: 5, social: 95, creativity: 20, narrative: 5 },
  { name: "Smite", challenge: 75, exploration: 5, social: 90, creativity: 15, narrative: 5 },

  { name: "Civilization VI", challenge: 75, exploration: 40, social: 30, creativity: 35, narrative: 20 },
  { name: "Civilization V", challenge: 75, exploration: 35, social: 25, creativity: 35, narrative: 20 },
  { name: "Age of Empires II", challenge: 80, exploration: 15, social: 50, creativity: 20, narrative: 15 },
  { name: "Age of Empires IV", challenge: 75, exploration: 15, social: 50, creativity: 20, narrative: 15 },
  { name: "StarCraft II", challenge: 95, exploration: 5, social: 60, creativity: 15, narrative: 15 },
  { name: "Crusader Kings III", challenge: 85, exploration: 35, social: 20, creativity: 80, narrative: 70 },
  { name: "Europa Universalis IV", challenge: 95, exploration: 30, social: 20, creativity: 70, narrative: 40 },
  { name: "XCOM 2", challenge: 85, exploration: 20, social: 5, creativity: 25, narrative: 50 },

  { name: "Subnautica", challenge: 55, exploration: 100, social: 0, creativity: 40, narrative: 50 },
  { name: "No Man's Sky", challenge: 35, exploration: 100, social: 40, creativity: 70, narrative: 20 },
  { name: "Valheim", challenge: 65, exploration: 90, social: 70, creativity: 65, narrative: 15 },
  { name: "ARK Survival Evolved", challenge: 75, exploration: 80, social: 80, creativity: 55, narrative: 10 },
  { name: "Rust", challenge: 85, exploration: 70, social: 95, creativity: 35, narrative: 5 },
  { name: "The Forest", challenge: 75, exploration: 70, social: 60, creativity: 25, narrative: 35 },
  { name: "Sons of the Forest", challenge: 75, exploration: 75, social: 60, creativity: 25, narrative: 40 },

  { name: "Rocket League", challenge: 85, exploration: 5, social: 90, creativity: 20, narrative: 0 },
  { name: "Forza Horizon 5", challenge: 40, exploration: 70, social: 60, creativity: 20, narrative: 5 },
  { name: "Need for Speed Heat", challenge: 45, exploration: 50, social: 40, creativity: 15, narrative: 25 },
  { name: "Trackmania", challenge: 90, exploration: 10, social: 40, creativity: 10, narrative: 0 },

  { name: "Resident Evil 4", challenge: 70, exploration: 40, social: 5, creativity: 5, narrative: 75 },
  { name: "Resident Evil 2", challenge: 75, exploration: 50, social: 5, creativity: 5, narrative: 75 },
  { name: "Silent Hill 2", challenge: 50, exploration: 40, social: 5, creativity: 5, narrative: 100 },
  { name: "Alien Isolation", challenge: 80, exploration: 50, social: 5, creativity: 5, narrative: 60 },

  { name: "Metal Gear Solid V", challenge: 70, exploration: 80, social: 5, creativity: 80, narrative: 80 },
  { name: "Metal Gear Solid 3", challenge: 65, exploration: 40, social: 5, creativity: 30, narrative: 95 },
  { name: "Death Stranding", challenge: 35, exploration: 90, social: 30, creativity: 20, narrative: 95 },

  { name: "Persona 5 Royal", challenge: 50, exploration: 35, social: 20, creativity: 15, narrative: 100 },
  { name: "Final Fantasy VII Remake", challenge: 55, exploration: 35, social: 15, creativity: 10, narrative: 95 },
  { name: "Chrono Trigger", challenge: 40, exploration: 45, social: 5, creativity: 10, narrative: 95 },
  { name: "Pokemon Emerald", challenge: 25, exploration: 70, social: 5, creativity: 10, narrative: 50 },
  { name: "Pokemon HeartGold", challenge: 25, exploration: 75, social: 5, creativity: 10, narrative: 50 }
];